### PR TITLE
Refactor Dashboard Admin Page to use Material Design Layout

### PR DESCRIPTION
**Pull request by jmuharsky**

### CODE REVIEW

**Comment by klausw** [comment]
Please rebase your patch, merge commits such as "Merge branch 'master' into material_admin" make the history and diffs very confusing.

**Comment by klausw** [comment]
Also, please follow [best practices](http://chris.beams.io/posts/git-commit/) for commit messages, the commit shows up like this since the first line is too long:

```
Refactor admin page HTML to use Material Design layout, fix upload da…
…shboard issue.
```

(If you have too many changes to be neatly summarized, that's often a hint they should be separate commits.)

**Comment by jmuharsky** [comment]
Cleaned up.  PTAL?

**Comment by klausw** [comment]
LGTM

**Pull request merged**
