### PR TITLE
Allow maximize widget from UI and URL.

### PR DESCRIPTION
**Pull request by jmuharsky**
**Maximize Widget**
* Widgets can now be maximized. Using the "arrows apart" button on the widget's top-right button set, it will focus on the widget and use the full page size. Clicking the "arrows together" button will restore the widget to normal size.
* The &maximize parameter is added to the URL when a widget is maximized. This allows you to share this state with other users, and when they open the dashboard the appropriate widget will be selected and maximized.

### CODE REVIEW

**Comment by jmuharsky** [comment]
googlebot, your vigilance is admirable, but perhaps a bit excessively so.  *ahem*

I signed it!

**Comment by jmuharsky** [comment]
This is deployed at https://28-dot-perfkit-explorer.appspot.com

**Comment by jmuharsky** [comment]
Demo posted at:

https://28-dot-perfkit-explorer.appspot.com/explore?dashboard=5714163003293696

**Comment by ivansmf** [comment]
We did an offline review, pulling this in.

**Pull request merged**
